[package]
name = "anyleaf_linux_example"
version = "0.1.0"
authors = ["Anyleaf <anyleaf@anyleaf.org>"]
edition = "2018"

[dependencies]
embedded-hal = "^0.2.4"
linux-embedded-hal = "^0.3.0"
anyleaf = "^0.1.8"